import EventEmitter from 'events';

const eventBus = new EventEmitter();

const EVENTS = {
    SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
    RECEIVE_CHAT_MESSAGE: 'RECEIVE_CHAT_MESSAGE',
    PLAYER_SELECTED: 'PLAYER_SELECTED',
    SEARCH_PLAYER_SELECTED: 'SEARCH_PLAYER_SELECTED',
    CHAT_MESSAGE: 'CHAT_MESSAGE',
    UPDATE_PLAYERS: 'UPDATE_PLAYERS',
    BUILDING_SELECTED: 'BUILDING_SELECTED',
    SELECT_AND_SHOW_INFO_PLAYER: 'SELECT_AND_SHOW_INFO_PLAYER',
    POST_RENDER: 'POST_RENDER',
    GAME_STATE_UPDATED: 'GAME_STATE_UPDATED',
    SWITCH_TO_BUILDING_INFO: 'SWITCH_TO_BUILDING_INFO'
};

export default eventBus;
export { EVENTS }; 